version: '3.4'

networks:
  monitor-net:

services:
  prometheus:
    image: "prom/prometheus:${PROMETHEUS_VERSION}"
    hostname: prometheus
    container_name: localprometheus
    ports:
      - 9090:9090
    volumes:
      - ./prom_volume/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitor-net
    restart: always

  grafana:
    image: "grafana/grafana:${GRAFANA_VERSION}"
    container_name: localgrafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana_volume/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana_volume/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      # - ./grafana.db:/var/lib/grafana/grafana.db
    depends_on:
      - prometheus
    networks:
      - monitor-net
    restart: always

  postgres_db:
    image: "postgres:${POSTGRES_VERSION}"
    container_name: localpostgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "password123"
    networks:
      - monitor-net
    healthcheck:
      test: ["CMD-SHELL", " netstat -an | grep -q 5432"]

  postgres_exporter:
    build:
      context: ./exporters/postgres_exporter/
    container_name: localpostgresexporter
    ports:
      - 8080:8000
    networks:
      - monitor-net
    restart: always
    depends_on:
      postgres_db:
        condition: service_healthy
